### ISSUE TITLE
Module2 Capstone project

### ISSUE THREAD

**Issue by AbdimulhinYussuf3675** [AbdimulhinYussuf3675/Mnet_Movie#21]
https://github.com/users/AbdimulhinYussuf3675/projects/1

This is the project link, we are a team of 3 members.

**Comment by TuyishimireEric** [comment]
# Status: REQUIRED CHANGES :recycle: 
### Hi  @Team 👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Highlights 
✔️ Professional PR. 👍
✔️ No linter errors👍
✔️ Professional README👍

## Required Changes ♻️

- [ ] for the kanban board, kindly make sure that all cards are assigned to team members. they will be a circle with the user's avatar on each card. See the example below:

   * ![Assigned cards example]
     ![image](https://user-images.githubusercontent.com/102757126/216988805-628161f8-385d-43f7-85a1-f98974acdcb7.png)

- [ ] Kindly remember, cards should be assigned to team members in a fair way:
    * you may decide who is `Student A`, `Student B`, and `Student C`. So each card with `Student A` in its title should always be assigned to the same student (and analogical for other students).
    * All cards with `group task` in the title should be assigned to someone (it does not matter to whom as students had freedom with that). 

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
